name: Backend Workflow
on:
  push:
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "build job is being run"
  lint:
    runs-on: ubuntu-latest
    steps:
    - run: echo "lint job is being run"
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Test job is being run"